### ISSUE TITLE
Request for infinite scroll

### ISSUE THREAD

**Issue by sebasbose** [JayTWWM/Image-Slider-Flutter#3]
Is there a plan or way to add infinite scroll to the Image Slider TabController? For examples being able to return to the first item in the list when trying to go pass through the last item.

**Comment by JayTWWM** [comment]
A way of doing it is attaching a listener to the tab controller and then animating it to the start as it reaches the end.
Something like this: [https://stackoverflow.com/questions/64186598/notificationlistener-in-tabcontroller-for-infinite-scroll](https://stackoverflow.com/questions/64186598/notificationlistener-in-tabcontroller-for-infinite-scroll)
